# Generated by Django 2.2.16 on 2021-09-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210917_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-username',)},
        ),
    ]
