# Generated by Django 2.2.16 on 2021-09-17 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210917_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10, 'Рейтинг не может быть выше 10'), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
    ]
