# Generated by Django 2.2.16 on 2021-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_title_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='score',
            new_name='rating',
        ),
    ]
