# Generated by Django 2.2.16 on 2021-09-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210917_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='rating',
            new_name='score',
        ),
    ]
